3.Importing Data
================
Michael Aung Kyaw
(19 juin, 2022)

# Dataset1 - Beaver 2

We load the dataset beaver 2 : data`beaver2`:

While there is actually two datasets of beaver, I chose to use beaver2,
since I used it in the 2nd markdown and though that it would be
interesting to investigate it in more details.

## Description of Beaver2

``` r
library(knitr)
kable(head(beaver2))
```

| day | time |  temp | activ |
|----:|-----:|------:|------:|
| 307 |  930 | 36.58 |     0 |
| 307 |  940 | 36.73 |     0 |
| 307 |  950 | 36.93 |     0 |
| 307 | 1000 | 37.15 |     0 |
| 307 | 1010 | 37.23 |     0 |
| 307 | 1020 | 37.24 |     0 |

``` r
str(beaver2)
```

    ## 'data.frame':    100 obs. of  4 variables:
    ##  $ day  : num  307 307 307 307 307 307 307 307 307 307 ...
    ##  $ time : num  930 940 950 1000 1010 1020 1030 1040 1050 1100 ...
    ##  $ temp : num  36.6 36.7 36.9 37.1 37.2 ...
    ##  $ activ: num  0 0 0 0 0 0 0 0 0 0 ...

We have shown the table of results showing only the “head” of the table
that is containing the first 6 entries of the dataset. Since we saw in
the previous markdown that the table was very long, I don’t think it is
necessary to show it entirely

So in our dataset we have…

-   **4 variables** composed of *100 observations*. The variables are:
    **day**, **time**, **temperature** and **activity**.
-   It seems that each of these four variables are *numerical*.
-   These measure would then all quantitative

## Descrption of Beaver2 dataset from Source

-   “**Reynolds (1994)** describes a small part of a study of the
    long-term temperature dynamics of beaver **Castor canadensis** in
    north-central Wisconsin. Body temperature was measured by telemetry
    every 10 minutes for four females, but data from a one period of
    less than a day for each of two animals is used there.”

-   **Day** :Day of observation (in days since the beginning of 1990),
    December 12–13 (beaver1) and November 3–4 (beaver2). - *Numerical
    variable*

-   **Time**: Time of observation, in the form 0330 for 3:30am -
    *Numerical variable*

-   **Temp**: Measured body temperature in degrees Celsius. - *Numerical
    variable*

-   **Activity**: Indicator of activity outside the retreat. -
    *Numerical variable*

## Picture of *Castor canadensis*

![](https://fr-academic.com/pictures/frwiki/67/Castor_canadensis.jpg)

## Source of Beaver2 dataset

-   **P. S. Reynolds (1994) Time-series analyses of beaver body
    temperatures. Chapter 11 of Lange, N., Ryan, L., Billard, L.,
    Brillinger, D., Conquest, L. and Greenhouse, J. eds (1994) Case
    Studies in Biometry. New York: John Wiley and Sons.**

-   **R: Body temperature series of two Beavers. (n.d.). Retrieved June
    19, 2022, from
    <https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/beavers.html>**

-   **<https://fr-academic.com/pictures/frwiki/67/Castor_canadensis.jpg>**

# Dataset 2 - Causes of Death in France

-   The second dataset is a data set different types of causes of death
    in France

``` r
library(readr)
CausesOfDeathFrance <- read_csv("CausesOfDeathFrance.csv")
```

    ## Rows: 1056 Columns: 8
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): GEO, UNIT, SEX, AGE, ICD10, Value
    ## dbl (1): TIME
    ## lgl (1): Flag and Footnotes
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
View(CausesOfDeathFrance)
kable(head(CausesOfDeathFrance))
```

| TIME | GEO    | UNIT   | SEX   | AGE   | ICD10                                               | Value   | Flag and Footnotes |
|-----:|:-------|:-------|:------|:------|:----------------------------------------------------|:--------|:-------------------|
| 2001 | France | Number | Males | Total | All causes of death (A00-Y89) excluding S00-T98     | 277 858 | NA                 |
| 2001 | France | Number | Males | Total | Certain infectious and parasitic diseases (A00-B99) | 5 347   | NA                 |
| 2001 | France | Number | Males | Total | Tuberculosis                                        | 545     | NA                 |
| 2001 | France | Number | Males | Total | Meningococcal infection                             | 30      | NA                 |
| 2001 | France | Number | Males | Total | Viral hepatitis                                     | 471     | NA                 |
| 2001 | France | Number | Males | Total | Human immunodeficiency virus \[HIV\] disease        | 892     | NA                 |

``` r
str(CausesOfDeathFrance)
```

    ## spec_tbl_df [1,056 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ TIME              : num [1:1056] 2001 2001 2001 2001 2001 ...
    ##  $ GEO               : chr [1:1056] "France" "France" "France" "France" ...
    ##  $ UNIT              : chr [1:1056] "Number" "Number" "Number" "Number" ...
    ##  $ SEX               : chr [1:1056] "Males" "Males" "Males" "Males" ...
    ##  $ AGE               : chr [1:1056] "Total" "Total" "Total" "Total" ...
    ##  $ ICD10             : chr [1:1056] "All causes of death (A00-Y89) excluding S00-T98" "Certain infectious and parasitic diseases (A00-B99)" "Tuberculosis" "Meningococcal infection" ...
    ##  $ Value             : chr [1:1056] "277 858" "5 347" "545" "30" ...
    ##  $ Flag and Footnotes: logi [1:1056] NA NA NA NA NA NA ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   TIME = col_double(),
    ##   ..   GEO = col_character(),
    ##   ..   UNIT = col_character(),
    ##   ..   SEX = col_character(),
    ##   ..   AGE = col_character(),
    ##   ..   ICD10 = col_character(),
    ##   ..   Value = col_character(),
    ##   ..   `Flag and Footnotes` = col_logical()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

## Despcrition of Death Causes in France dataset eurostat

The dataset CausesOfDeathFrance in composed of *8 variables*

-   **Time** : quantitaive variable

-   **Geo** : qualitative variable

-   **Unit**: qualitative variable

-   **Sex**: qualitative variable

-   **Age**: qualitative variable

-   **ICD10**: qualitative variable

-   **Value**: qualitative variable

-   **Flag and Footnotes** :qualitative variable

-   We have a total of *1056 observations*

## Description of hapiness dataset from the source

-   **Data on causes of death (COD)** provide information on
    \***mortality patterns** and form a major element of **public health
    information**.

-   The COD data refer to the underlying cause which - according to the
    **World Health Organisation (WHO)** - is “the disease or injury
    which initiated the train of morbid events leading directly to
    death, or the circumstances of the accident or violence which
    produced the fatal injury”.

-   Data published in **Eurobase\* are broken down by ***sex***,**\*
    5-year age groups***, ***cause of death\*\*\* and by ***residency***
    and \***country of occurrence**. For stillbirths and neonatal
    deaths, additional breakdowns might include age of mother and parity

## Picture of France with capitals in Europe

![](https://cdn.britannica.com/42/183642-050-C7D21FE8/World-Data-Locator-Map-France.jpg)

## Source of CausesOfDeathFrance dataset

-   The data set comes from the website *EuroStat*
-   URL :
    **<http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=hlth_cd_anr&lang=en>**
-   PICTURE :
    **<https://cdn.britannica.com/42/183642-050-C7D21FE8/World-Data-Locator-Map-France.jpg>**

# Dataset 3 - Happiness

## Description of happiness dataset

-   European quality of life survey with questions related to income,
    life satisfaction or perceived quality of society.
-   Provides the average rating for the question How happy would you say
    you are these days? Rating 1 (low) to 10 (high) by country and by
    sex.

``` r
library(readr)
happiness <- read_csv("happiness.csv")
```

    ## Rows: 105 Columns: 4
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): Country, Gender
    ## dbl (2): Mean, N=
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
View(happiness)
kable(head(happiness))
```

| Country | Gender | Mean |   N= |
|:--------|:-------|-----:|-----:|
| AT      | Male   |  7.3 |  471 |
| NA      | Female |  7.3 |  570 |
| NA      | Both   |  7.3 | 1041 |
| BE      | Male   |  7.8 |  468 |
| NA      | Female |  7.8 |  542 |
| NA      | Both   |  7.8 | 1010 |

``` r
str(happiness)
```

    ## spec_tbl_df [105 × 4] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Country: chr [1:105] "AT" NA NA "BE" ...
    ##  $ Gender : chr [1:105] "Male" "Female" "Both" "Male" ...
    ##  $ Mean   : num [1:105] 7.3 7.3 7.3 7.8 7.8 7.8 5.8 5.8 5.8 7.8 ...
    ##  $ N=     : num [1:105] 471 570 1041 468 542 ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   Country = col_character(),
    ##   ..   Gender = col_character(),
    ##   ..   Mean = col_double(),
    ##   ..   `N=` = col_double()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
spec(happiness)
```

    ## cols(
    ##   Country = col_character(),
    ##   Gender = col_character(),
    ##   Mean = col_double(),
    ##   `N=` = col_double()
    ## )

## Source of the Film datase

## Despcrition of Hapiness dataset variables

-   In the happiness dataset R recognizes 4 variables for 105
    observations
-   In reality we have 2 variables

## Variables of Hapiness dataset

-   Gender : Qualitative numerical variable
-   Country: Qualitative nominal variable

## Small comic in link with hapiness

![](https://images.squarespace-cdn.com/content/v1/5bc04bb5b10f257212a8dca7/1567120904020-73X04QNHQJ72C0X22I25/feat_800px.jpg?format=1000w)

## Source of the Hapiness dataset

-   **<https://perso.telecom-paristech.fr/eagan/class/igr204/datasets>**
-   Picture by *zen pencils* found on
    **<https://images.squarespace-cdn.com/content/v1/5bc04bb5b10f257212a8dca7/1567120904020-73X04QNHQJ72C0X22I25/feat_800px.jpg?format=1000w>**
